### ISSUE TITLE
How to embed in an iframe?

### ISSUE THREAD

**Issue by emorling** [cb-vivek/chargebee-checkout-samples#1]
Do you have an example of how to embed the checkout in an iframe using react? Thanks

**Comment by cb-vivek** [comment]
You can use chargebee.js in react to open your checkout in a modal box(iframe). We suggest you to use our js to open the checkout pages inside an iframe.

https://github.com/cb-vivek/chargebee-checkout-samples/blob/master/api/front-end/react-app/src/App.js

**Comment by emorling** [comment]
I have a couple of questions:
1. The documentation talks about embed=true to open an iframe in cbInstance.openCheckout. Is this not required?
2. I am using the code from App.js but it's opening a new window. Should it be opening in an iframe?

**Comment by cb-vivek** [comment]
1. pass embed=false if you want to show paypal, amazon pay and apple pay payment methods to your customers. It has nothing to do with iframe.
2. Checkout will be opened in a new window only in case of mobile browsers. It will be opened inside an iframe in case of desktop browsers.

Can you share your code snippet? So that I can have a look at it. Screencast of the behavior would also be helpful.

**Comment by emorling** [comment]
Okay thanks that sorted it.
1. Thanks, now I understand
2. You are right. I was using developer tools in Chrome and had the window adjusted to a mobile, so I wasnt seeing the iframe
